auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: tylderen
url: http://tylderen.github.io
feed: /atom.xml
author_info: <a href="http://tylderen.github.io">tylderen</a>
